# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/rxb9zl1mdx9f2n3z0nyv9zhngj3f2pw0-cmake-3.24.3/bin/cmake

# The command to remove a file.
RM = /nix/store/rxb9zl1mdx9f2n3z0nyv9zhngj3f2pw0-cmake-3.24.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/SistemaBancario

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/SistemaBancario

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/nix/store/rxb9zl1mdx9f2n3z0nyv9zhngj3f2pw0-cmake-3.24.3/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/nix/store/rxb9zl1mdx9f2n3z0nyv9zhngj3f2pw0-cmake-3.24.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/SistemaBancario/CMakeFiles /home/runner/SistemaBancario//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/SistemaBancario/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Sistema_Bancario

# Build rule for target.
Sistema_Bancario: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Sistema_Bancario
.PHONY : Sistema_Bancario

# fast build rule for target.
Sistema_Bancario/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sistema_Bancario.dir/build.make CMakeFiles/Sistema_Bancario.dir/build
.PHONY : Sistema_Bancario/fast

Account.o: Account.cpp.o
.PHONY : Account.o

# target to build an object file
Account.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sistema_Bancario.dir/build.make CMakeFiles/Sistema_Bancario.dir/Account.cpp.o
.PHONY : Account.cpp.o

Account.i: Account.cpp.i
.PHONY : Account.i

# target to preprocess a source file
Account.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sistema_Bancario.dir/build.make CMakeFiles/Sistema_Bancario.dir/Account.cpp.i
.PHONY : Account.cpp.i

Account.s: Account.cpp.s
.PHONY : Account.s

# target to generate assembly for a file
Account.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sistema_Bancario.dir/build.make CMakeFiles/Sistema_Bancario.dir/Account.cpp.s
.PHONY : Account.cpp.s

Bank.o: Bank.cpp.o
.PHONY : Bank.o

# target to build an object file
Bank.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sistema_Bancario.dir/build.make CMakeFiles/Sistema_Bancario.dir/Bank.cpp.o
.PHONY : Bank.cpp.o

Bank.i: Bank.cpp.i
.PHONY : Bank.i

# target to preprocess a source file
Bank.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sistema_Bancario.dir/build.make CMakeFiles/Sistema_Bancario.dir/Bank.cpp.i
.PHONY : Bank.cpp.i

Bank.s: Bank.cpp.s
.PHONY : Bank.s

# target to generate assembly for a file
Bank.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sistema_Bancario.dir/build.make CMakeFiles/Sistema_Bancario.dir/Bank.cpp.s
.PHONY : Bank.cpp.s

CheckingAccount.o: CheckingAccount.cpp.o
.PHONY : CheckingAccount.o

# target to build an object file
CheckingAccount.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sistema_Bancario.dir/build.make CMakeFiles/Sistema_Bancario.dir/CheckingAccount.cpp.o
.PHONY : CheckingAccount.cpp.o

CheckingAccount.i: CheckingAccount.cpp.i
.PHONY : CheckingAccount.i

# target to preprocess a source file
CheckingAccount.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sistema_Bancario.dir/build.make CMakeFiles/Sistema_Bancario.dir/CheckingAccount.cpp.i
.PHONY : CheckingAccount.cpp.i

CheckingAccount.s: CheckingAccount.cpp.s
.PHONY : CheckingAccount.s

# target to generate assembly for a file
CheckingAccount.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sistema_Bancario.dir/build.make CMakeFiles/Sistema_Bancario.dir/CheckingAccount.cpp.s
.PHONY : CheckingAccount.cpp.s

SavingsAccount.o: SavingsAccount.cpp.o
.PHONY : SavingsAccount.o

# target to build an object file
SavingsAccount.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sistema_Bancario.dir/build.make CMakeFiles/Sistema_Bancario.dir/SavingsAccount.cpp.o
.PHONY : SavingsAccount.cpp.o

SavingsAccount.i: SavingsAccount.cpp.i
.PHONY : SavingsAccount.i

# target to preprocess a source file
SavingsAccount.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sistema_Bancario.dir/build.make CMakeFiles/Sistema_Bancario.dir/SavingsAccount.cpp.i
.PHONY : SavingsAccount.cpp.i

SavingsAccount.s: SavingsAccount.cpp.s
.PHONY : SavingsAccount.s

# target to generate assembly for a file
SavingsAccount.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sistema_Bancario.dir/build.make CMakeFiles/Sistema_Bancario.dir/SavingsAccount.cpp.s
.PHONY : SavingsAccount.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sistema_Bancario.dir/build.make CMakeFiles/Sistema_Bancario.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sistema_Bancario.dir/build.make CMakeFiles/Sistema_Bancario.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Sistema_Bancario.dir/build.make CMakeFiles/Sistema_Bancario.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Sistema_Bancario"
	@echo "... Account.o"
	@echo "... Account.i"
	@echo "... Account.s"
	@echo "... Bank.o"
	@echo "... Bank.i"
	@echo "... Bank.s"
	@echo "... CheckingAccount.o"
	@echo "... CheckingAccount.i"
	@echo "... CheckingAccount.s"
	@echo "... SavingsAccount.o"
	@echo "... SavingsAccount.i"
	@echo "... SavingsAccount.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

